# LICENSE MANIFEST 
#
# This TOML document summarizes licensing information for external/third-party 
# software packages used in this repository. The licenses themselves are contained
# within the same folder structure containing this document and are indicated for 
# each package.

["jQuery blockUI plugin"]
source      = "https://github.com/malsup/blockui/"
version     = "2.70.0-2014.11.23"
author      = "M. Alsup"
licenseType = "MIT"
license     = "jQuery blockUI plugin/LICENSE-INFO.txt"
usage       = "/src/Client/wwwroot/scripts/ext/jquery.blockUI.js"
notes       = "The license language is specified via reference in the copyright notice in the comment headers of the source."

[jQuery]
source      = "https://code.jquery.com/jquery-3.6.0.min.js"
version     = "3.6.0"
author      = "OpenJS Foundation and jQuery contributors"
licenseType = "MIT"
license     = "jQuery/LICENSE-INFO.txt"
usage       = "/src/Client/wwwroot/scripts/ext/jquery-3.6.0.min.js"
notes       = "The license language is specified via reference in the copyright notice in the comment headers of the source."
