#pragma checksum "D:\Code\GakuGym\public\src\Client\Pages\EditFact.razor" "{8829d00f-11b8-4213-878b-770e8597ac16}" "7d98d63aba9920e7b91c41505e98ed75bef6caff486b94acdbb3fd5d5f24ebb4"
// <auto-generated/>
#pragma warning disable 1591
namespace GakuGym.Client.Pages
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Components;
#nullable restore
#line 1 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using System.Net.Http;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using System.Net.Http.Json;

#line default
#line hidden
#nullable disable
#nullable restore
#line 3 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using Microsoft.AspNetCore.Components.Forms;

#line default
#line hidden
#nullable disable
#nullable restore
#line 4 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using Microsoft.AspNetCore.Components.Routing;

#line default
#line hidden
#nullable disable
#nullable restore
#line 5 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using Microsoft.AspNetCore.Components.Web;

#line default
#line hidden
#nullable disable
#nullable restore
#line 6 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using Microsoft.AspNetCore.Components.WebAssembly.Http;

#line default
#line hidden
#nullable disable
#nullable restore
#line 7 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using Microsoft.JSInterop;

#line default
#line hidden
#nullable disable
#nullable restore
#line 8 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using GakuGym.Client;

#line default
#line hidden
#nullable disable
#nullable restore
#line 9 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using GakuGym.Common;

#line default
#line hidden
#nullable disable
    [Microsoft.AspNetCore.Components.RouteAttribute("/fact-database/fact/{RouteFactId:guid}/edit")]
    public partial class EditFact : BaseComponent
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
#nullable restore
#line 5 "D:\Code\GakuGym\public\src\Client\Pages\EditFact.razor"
 if(category != null && fieldValues != null)
{

#line default
#line hidden
#nullable disable
            __builder.OpenElement(0, "div");
            __builder.AddAttribute(1, "id", "pageHeader");
            __builder.OpenElement(2, "span");
            __builder.AddAttribute(3, "id", "pageHeaderLeft");
#nullable restore
#line (8,33)-(8,46) 24 "D:\Code\GakuGym\public\src\Client\Pages\EditFact.razor"
__builder.AddContent(4, category.name);

#line default
#line hidden
#nullable disable
            __builder.AddContent(5, " - New Fact");
            __builder.CloseElement();
            __builder.AddMarkupContent(6, "\n\t\t");
            __builder.OpenElement(7, "span");
            __builder.AddAttribute(8, "id", "pageHeaderRight");
            __builder.OpenElement(9, "button");
            __builder.AddAttribute(10, "class", "SecondaryButton");
            __builder.AddAttribute(11, "onclick", Microsoft.AspNetCore.Components.EventCallback.Factory.Create<Microsoft.AspNetCore.Components.Web.MouseEventArgs>(this, 
#nullable restore
#line 10 "D:\Code\GakuGym\public\src\Client\Pages\EditFact.razor"
                                                      OnCloseClick

#line default
#line hidden
#nullable disable
            ));
            __builder.AddMarkupContent(12, "<svg class=\"icon\"><use xlink:href=\"#close\"></use></svg>");
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.AddMarkupContent(13, "\n\t");
            __builder.OpenElement(14, "div");
            __builder.AddAttribute(15, "id", "pageBody");
#nullable restore
#line 15 "D:\Code\GakuGym\public\src\Client\Pages\EditFact.razor"
         foreach(var field in fieldValues)
		{

#line default
#line hidden
#nullable disable
            __builder.OpenElement(16, "div");
            __builder.AddAttribute(17, "class", "inputWrapper");
            __builder.OpenElement(18, "label");
#nullable restore
#line (18,13)-(18,28) 25 "D:\Code\GakuGym\public\src\Client\Pages\EditFact.razor"
__builder.AddContent(19, field.fieldName);

#line default
#line hidden
#nullable disable
            __builder.CloseElement();
            __builder.AddMarkupContent(20, "\n\t\t\t\t");
            __builder.OpenElement(21, "input");
            __builder.AddAttribute(22, "type", "text");
            __builder.AddAttribute(23, "value", Microsoft.AspNetCore.Components.BindConverter.FormatValue(
#nullable restore
#line 19 "D:\Code\GakuGym\public\src\Client\Pages\EditFact.razor"
                                                 field.value

#line default
#line hidden
#nullable disable
            ));
            __builder.AddAttribute(24, "onchange", Microsoft.AspNetCore.Components.EventCallback.Factory.CreateBinder(this, __value => field.value = __value, field.value));
            __builder.SetUpdatesAttributeName("value");
            __builder.CloseElement();
            __builder.CloseElement();
#nullable restore
#line 21 "D:\Code\GakuGym\public\src\Client\Pages\EditFact.razor"
		}

#line default
#line hidden
#nullable disable
            __builder.OpenElement(25, "div");
            __builder.OpenElement(26, "button");
            __builder.AddAttribute(27, "onclick", Microsoft.AspNetCore.Components.EventCallback.Factory.Create<Microsoft.AspNetCore.Components.Web.MouseEventArgs>(this, 
#nullable restore
#line 23 "D:\Code\GakuGym\public\src\Client\Pages\EditFact.razor"
                              OnSaveFactClick

#line default
#line hidden
#nullable disable
            ));
            __builder.AddContent(28, "Save Fact");
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.CloseElement();
#nullable restore
#line 26 "D:\Code\GakuGym\public\src\Client\Pages\EditFact.razor"
}

#line default
#line hidden
#nullable disable
        }
        #pragma warning restore 1998
#nullable restore
#line 29 "D:\Code\GakuGym\public\src\Client\Pages\EditFact.razor"
 
	[Parameter]
	public Guid RouteFactId { get; set; }

	class FactFieldModel
	{
		public Guid guid;
		public string fieldName;
		public string value;
	}

    List<FactFieldModel>? fieldValues;
	Fact?                 fact;
	Category?             category;

	protected override async Task OnParametersSetAsync()
	{
		fact     = await API.GetFact(RouteFactId);
		category = await API.GetCategory(fact.categoryId);

		fieldValues = category.fields.Select(x => new FactFieldModel 
		{ 
			guid      = x.guid, 
			fieldName = x.name, 
			value     = fact.fieldData[x.guid] 
		}).ToList();		
	}

	void OnCloseClick()
	{
		NavigationManager.NavigateTo($"/fact-database/category/{fact.categoryId}");		
	}

	async Task OnSaveFactClick()
	{
		await API.UpdateFact(new Fact
		{
			guid      = fact.guid,
			fieldData = fieldValues.ToDictionary(x => x.guid, x => x.value)
		});

		NavigationManager.NavigateTo($"/fact-database/category/{category.guid}");
	}

#line default
#line hidden
#nullable disable
    }
}
#pragma warning restore 1591
