#pragma checksum "D:\Code\GakuGym\public\src\Client\Pages\AddCategory.razor" "{8829d00f-11b8-4213-878b-770e8597ac16}" "a7609bafdb8cd2a75da0b80d7c7e961c9e4e83384f7827f07f28bbfefad41b99"
// <auto-generated/>
#pragma warning disable 1591
namespace GakuGym.Client.Pages
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Components;
#nullable restore
#line 1 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using System.Net.Http;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using System.Net.Http.Json;

#line default
#line hidden
#nullable disable
#nullable restore
#line 3 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using Microsoft.AspNetCore.Components.Forms;

#line default
#line hidden
#nullable disable
#nullable restore
#line 4 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using Microsoft.AspNetCore.Components.Routing;

#line default
#line hidden
#nullable disable
#nullable restore
#line 5 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using Microsoft.AspNetCore.Components.Web;

#line default
#line hidden
#nullable disable
#nullable restore
#line 6 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using Microsoft.AspNetCore.Components.WebAssembly.Http;

#line default
#line hidden
#nullable disable
#nullable restore
#line 7 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using Microsoft.JSInterop;

#line default
#line hidden
#nullable disable
#nullable restore
#line 8 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using GakuGym.Client;

#line default
#line hidden
#nullable disable
#nullable restore
#line 9 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using GakuGym.Common;

#line default
#line hidden
#nullable disable
    [Microsoft.AspNetCore.Components.RouteAttribute("/fact-database/domain/{RouteDomainId:guid}/add-category")]
    public partial class AddCategory : BaseComponent
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.OpenElement(0, "div");
            __builder.AddAttribute(1, "id", "pageHeader");
            __builder.AddMarkupContent(2, "<span id=\"pageHeaderLeft\">Add Category</span>\n\t");
            __builder.OpenElement(3, "span");
            __builder.AddAttribute(4, "id", "pageHeaderRight");
            __builder.OpenElement(5, "button");
            __builder.AddAttribute(6, "class", "SecondaryButton");
            __builder.AddAttribute(7, "onclick", Microsoft.AspNetCore.Components.EventCallback.Factory.Create<Microsoft.AspNetCore.Components.Web.MouseEventArgs>(this, 
#nullable restore
#line 6 "D:\Code\GakuGym\public\src\Client\Pages\AddCategory.razor"
                                                                         OnCloseClick

#line default
#line hidden
#nullable disable
            ));
            __builder.AddMarkupContent(8, "<svg class=\"icon\"><use xlink:href=\"#close\"></use></svg>");
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.AddMarkupContent(9, "\n");
            __builder.OpenElement(10, "div");
            __builder.AddAttribute(11, "id", "pageBody");
            __builder.OpenElement(12, "div");
            __builder.AddAttribute(13, "class", "inputWrapper");
            __builder.AddMarkupContent(14, "<label>Name</label>\n\t\t");
            __builder.OpenElement(15, "input");
            __builder.AddAttribute(16, "type", "text");
            __builder.AddAttribute(17, "value", Microsoft.AspNetCore.Components.BindConverter.FormatValue(
#nullable restore
#line 12 "D:\Code\GakuGym\public\src\Client\Pages\AddCategory.razor"
                                        categoryNameText

#line default
#line hidden
#nullable disable
            ));
            __builder.AddAttribute(18, "onchange", Microsoft.AspNetCore.Components.EventCallback.Factory.CreateBinder(this, __value => categoryNameText = __value, categoryNameText));
            __builder.SetUpdatesAttributeName("value");
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.AddMarkupContent(19, "\n\t");
            __builder.OpenElement(20, "div");
            __builder.AddAttribute(21, "class", "inputWrapper");
            __builder.AddMarkupContent(22, "<label>Description</label>\n\t\t");
            __builder.OpenElement(23, "input");
            __builder.AddAttribute(24, "type", "text");
            __builder.AddAttribute(25, "value", Microsoft.AspNetCore.Components.BindConverter.FormatValue(
#nullable restore
#line 16 "D:\Code\GakuGym\public\src\Client\Pages\AddCategory.razor"
                                        categoryDescriptionText

#line default
#line hidden
#nullable disable
            ));
            __builder.AddAttribute(26, "onchange", Microsoft.AspNetCore.Components.EventCallback.Factory.CreateBinder(this, __value => categoryDescriptionText = __value, categoryDescriptionText));
            __builder.SetUpdatesAttributeName("value");
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.AddMarkupContent(27, "\n\t");
            __builder.OpenElement(28, "div");
            __builder.AddAttribute(29, "class", "listHeader");
            __builder.AddMarkupContent(30, "<span>Fields</span>\n\t\t");
            __builder.OpenElement(31, "button");
            __builder.AddAttribute(32, "class", "SecondaryButton");
            __builder.AddAttribute(33, "onclick", Microsoft.AspNetCore.Components.EventCallback.Factory.Create<Microsoft.AspNetCore.Components.Web.MouseEventArgs>(this, 
#nullable restore
#line 20 "D:\Code\GakuGym\public\src\Client\Pages\AddCategory.razor"
                                                  OnAddFieldClick

#line default
#line hidden
#nullable disable
            ));
            __builder.AddMarkupContent(34, "<svg class=\"icon\"><use xlink:href=\"#add\"></use></svg>");
            __builder.CloseElement();
            __builder.CloseElement();
#nullable restore
#line 23 "D:\Code\GakuGym\public\src\Client\Pages\AddCategory.razor"
     foreach(var field in fields)
	{

#line default
#line hidden
#nullable disable
            __builder.OpenElement(35, "div");
            __builder.OpenElement(36, "div");
            __builder.AddAttribute(37, "class", "inputWrapper");
            __builder.AddMarkupContent(38, "<label>Name</label> \n\t\t\t\t");
            __builder.OpenElement(39, "input");
            __builder.AddAttribute(40, "type", "text");
            __builder.AddAttribute(41, "value", Microsoft.AspNetCore.Components.BindConverter.FormatValue(
#nullable restore
#line 28 "D:\Code\GakuGym\public\src\Client\Pages\AddCategory.razor"
                                                field.name

#line default
#line hidden
#nullable disable
            ));
            __builder.AddAttribute(42, "onchange", Microsoft.AspNetCore.Components.EventCallback.Factory.CreateBinder(this, __value => field.name = __value, field.name));
            __builder.SetUpdatesAttributeName("value");
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.AddMarkupContent(43, "\n\t\t\t");
            __builder.OpenElement(44, "div");
            __builder.AddAttribute(45, "class", "inputWrapper");
            __builder.OpenElement(46, "input");
            __builder.AddAttribute(47, "type", "text");
            __builder.AddAttribute(48, "value", Microsoft.AspNetCore.Components.BindConverter.FormatValue(
#nullable restore
#line 31 "D:\Code\GakuGym\public\src\Client\Pages\AddCategory.razor"
                                                field.description

#line default
#line hidden
#nullable disable
            ));
            __builder.AddAttribute(49, "onchange", Microsoft.AspNetCore.Components.EventCallback.Factory.CreateBinder(this, __value => field.description = __value, field.description));
            __builder.SetUpdatesAttributeName("value");
            __builder.CloseElement();
            __builder.AddMarkupContent(50, "\n\t\t\t\t");
            __builder.AddMarkupContent(51, "<label>Description</label>");
            __builder.CloseElement();
            __builder.AddMarkupContent(52, "\n\t\t\t");
            __builder.OpenElement(53, "div");
            __builder.AddAttribute(54, "class", "inputWrapper");
            __builder.OpenElement(55, "select");
            __builder.OpenElement(56, "option");
            __builder.AddContent(57, "Text");
            __builder.CloseElement();
            __builder.AddMarkupContent(58, "\n\t\t\t\t\t");
            __builder.OpenElement(59, "option");
            __builder.AddContent(60, "HTML");
            __builder.CloseElement();
            __builder.AddMarkupContent(61, "\n\t\t\t\t\t");
            __builder.OpenElement(62, "option");
            __builder.AddContent(63, "Image");
            __builder.CloseElement();
            __builder.AddMarkupContent(64, "\n\t\t\t\t\t");
            __builder.OpenElement(65, "option");
            __builder.AddContent(66, "Audio");
            __builder.CloseElement();
            __builder.AddMarkupContent(67, "\n\t\t\t\t\t");
            __builder.OpenElement(68, "option");
            __builder.AddContent(69, "Numeric");
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.AddMarkupContent(70, "\n\t\t\t\t");
            __builder.AddMarkupContent(71, "<label>Interpretation</label>");
            __builder.CloseElement();
            __builder.AddMarkupContent(72, "\n\t\t\t");
            __builder.OpenElement(73, "button");
            __builder.AddAttribute(74, "onclick", Microsoft.AspNetCore.Components.EventCallback.Factory.Create<Microsoft.AspNetCore.Components.Web.MouseEventArgs>(this, 
#nullable restore
#line 44 "D:\Code\GakuGym\public\src\Client\Pages\AddCategory.razor"
                              () => OnRemoveFieldClick(field)

#line default
#line hidden
#nullable disable
            ));
            __builder.AddContent(75, "Remove");
            __builder.CloseElement();
            __builder.CloseElement();
#nullable restore
#line 46 "D:\Code\GakuGym\public\src\Client\Pages\AddCategory.razor"
	}

#line default
#line hidden
#nullable disable
            __builder.OpenElement(76, "button");
            __builder.AddAttribute(77, "onclick", Microsoft.AspNetCore.Components.EventCallback.Factory.Create<Microsoft.AspNetCore.Components.Web.MouseEventArgs>(this, 
#nullable restore
#line 47 "D:\Code\GakuGym\public\src\Client\Pages\AddCategory.razor"
                      OnCreateButtonClick

#line default
#line hidden
#nullable disable
            ));
            __builder.AddContent(78, "Create");
            __builder.CloseElement();
            __builder.CloseElement();
        }
        #pragma warning restore 1998
#nullable restore
#line 50 "D:\Code\GakuGym\public\src\Client\Pages\AddCategory.razor"
 
	[Parameter]
	public Guid RouteDomainId { get; set; }

	string? categoryNameText;
	string? categoryDescriptionText;

	class CategoryField
	{
		public string? name;
		public string? description;
		public string? interpretation;
	}

    List<CategoryField> fields = new();

	void OnCloseClick()
	{
		NavigationManager.NavigateTo($"/fact-database/domain/{RouteDomainId}");		
	}

	void OnAddFieldClick()
	{
		fields.Add(new());
	}

	void OnRemoveFieldClick(CategoryField categoryField)
	{
		fields.Remove(categoryField);
	}

	async Task OnCreateButtonClick()
	{
		await API.CreateCategory(RouteDomainId, categoryNameText, categoryDescriptionText, fields.Select(x => (x.name, x.description, FieldType.Text)).ToList());

		NavigationManager.NavigateTo($"/fact-database/domain/{RouteDomainId}");
	}

#line default
#line hidden
#nullable disable
    }
}
#pragma warning restore 1591
