#pragma checksum "D:\Code\GakuGym\public\src\Client\Pages\CategoryPage.razor" "{8829d00f-11b8-4213-878b-770e8597ac16}" "fe0beb842e324f83246b0dda8c26f37b41fb516828e66ae96f4d9530834ecb05"
// <auto-generated/>
#pragma warning disable 1591
namespace GakuGym.Client.Pages
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Components;
#nullable restore
#line 1 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using System.Net.Http;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using System.Net.Http.Json;

#line default
#line hidden
#nullable disable
#nullable restore
#line 3 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using Microsoft.AspNetCore.Components.Forms;

#line default
#line hidden
#nullable disable
#nullable restore
#line 4 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using Microsoft.AspNetCore.Components.Routing;

#line default
#line hidden
#nullable disable
#nullable restore
#line 5 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using Microsoft.AspNetCore.Components.Web;

#line default
#line hidden
#nullable disable
#nullable restore
#line 6 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using Microsoft.AspNetCore.Components.WebAssembly.Http;

#line default
#line hidden
#nullable disable
#nullable restore
#line 7 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using Microsoft.JSInterop;

#line default
#line hidden
#nullable disable
#nullable restore
#line 8 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using GakuGym.Client;

#line default
#line hidden
#nullable disable
#nullable restore
#line 9 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using GakuGym.Common;

#line default
#line hidden
#nullable disable
    [Microsoft.AspNetCore.Components.RouteAttribute("/fact-database/category/{RouteParamCategoryId:guid}")]
    public partial class CategoryPage : BaseComponent
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
#nullable restore
#line 4 "D:\Code\GakuGym\public\src\Client\Pages\CategoryPage.razor"
 if(category != null)
{

#line default
#line hidden
#nullable disable
            __builder.OpenElement(0, "div");
            __builder.AddAttribute(1, "id", "pageHeader");
            __builder.OpenElement(2, "span");
            __builder.AddAttribute(3, "id", "pageHeaderLeft");
            __builder.AddContent(4, "Category - ");
#nullable restore
#line (7,44)-(7,57) 24 "D:\Code\GakuGym\public\src\Client\Pages\CategoryPage.razor"
__builder.AddContent(5, category.name);

#line default
#line hidden
#nullable disable
            __builder.CloseElement();
            __builder.AddMarkupContent(6, "\n\t\t");
            __builder.OpenElement(7, "span");
            __builder.AddAttribute(8, "id", "pageHeaderRight");
            __builder.OpenElement(9, "button");
            __builder.AddAttribute(10, "class", "SecondaryButton");
            __builder.AddAttribute(11, "onclick", Microsoft.AspNetCore.Components.EventCallback.Factory.Create<Microsoft.AspNetCore.Components.Web.MouseEventArgs>(this, 
#nullable restore
#line 9 "D:\Code\GakuGym\public\src\Client\Pages\CategoryPage.razor"
                                                      OnEditClick

#line default
#line hidden
#nullable disable
            ));
            __builder.AddMarkupContent(12, "<svg class=\"icon\"><use xlink:href=\"#edit\"></use></svg>");
            __builder.CloseElement();
            __builder.OpenElement(13, "button");
            __builder.AddAttribute(14, "class", "SecondaryButton");
            __builder.AddAttribute(15, "onclick", Microsoft.AspNetCore.Components.EventCallback.Factory.Create<Microsoft.AspNetCore.Components.Web.MouseEventArgs>(this, 
#nullable restore
#line 10 "D:\Code\GakuGym\public\src\Client\Pages\CategoryPage.razor"
                                                      OnBackClick

#line default
#line hidden
#nullable disable
            ));
            __builder.AddMarkupContent(16, "<svg class=\"icon\"><use xlink:href=\"#back\"></use></svg>");
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.AddMarkupContent(17, "\n\t");
            __builder.OpenElement(18, "div");
            __builder.AddAttribute(19, "id", "pageBody");
            __builder.OpenElement(20, "div");
#nullable restore
#line (15,9)-(15,29) 25 "D:\Code\GakuGym\public\src\Client\Pages\CategoryPage.razor"
__builder.AddContent(21, category.description);

#line default
#line hidden
#nullable disable
            __builder.CloseElement();
            __builder.AddMarkupContent(22, "\n\n\t\t");
            __builder.OpenElement(23, "div");
            __builder.AddAttribute(24, "class", "listHeader");
            __builder.AddMarkupContent(25, "<span>Challenges</span>\n\t\t\t");
            __builder.OpenElement(26, "button");
            __builder.AddAttribute(27, "class", "SecondaryButton");
            __builder.AddAttribute(28, "onclick", Microsoft.AspNetCore.Components.EventCallback.Factory.Create<Microsoft.AspNetCore.Components.Web.MouseEventArgs>(this, 
#nullable restore
#line 19 "D:\Code\GakuGym\public\src\Client\Pages\CategoryPage.razor"
                                                      OnAddChallengeClick

#line default
#line hidden
#nullable disable
            ));
            __builder.AddMarkupContent(29, "<svg class=\"icon\"><use xlink:href=\"#add\"></use></svg>");
            __builder.CloseElement();
            __builder.CloseElement();
#nullable restore
#line 21 "D:\Code\GakuGym\public\src\Client\Pages\CategoryPage.razor"
         if(challenges != null && challenges.Count > 0)
		{
			

#line default
#line hidden
#nullable disable
#nullable restore
#line 23 "D:\Code\GakuGym\public\src\Client\Pages\CategoryPage.razor"
             foreach(var challenge in challenges)
			{

#line default
#line hidden
#nullable disable
            __builder.OpenElement(30, "div");
#nullable restore
#line (26,7)-(26,21) 25 "D:\Code\GakuGym\public\src\Client\Pages\CategoryPage.razor"
__builder.AddContent(31, challenge.name);

#line default
#line hidden
#nullable disable
            __builder.AddMarkupContent(32, "\n\t\t\t\t\t");
            __builder.OpenElement(33, "button");
            __builder.AddAttribute(34, "class", "SecondaryButton");
            __builder.AddAttribute(35, "onclick", Microsoft.AspNetCore.Components.EventCallback.Factory.Create<Microsoft.AspNetCore.Components.Web.MouseEventArgs>(this, 
#nullable restore
#line 27 "D:\Code\GakuGym\public\src\Client\Pages\CategoryPage.razor"
                                                              () => OnEditChallenge(challenge)

#line default
#line hidden
#nullable disable
            ));
            __builder.AddMarkupContent(36, "<svg class=\"icon\"><use xlink:href=\"#edit\"></use></svg>");
            __builder.CloseElement();
            __builder.CloseElement();
#nullable restore
#line 29 "D:\Code\GakuGym\public\src\Client\Pages\CategoryPage.razor"
			}

#line default
#line hidden
#nullable disable
#nullable restore
#line 29 "D:\Code\GakuGym\public\src\Client\Pages\CategoryPage.razor"
             
		}
		else
		{

#line default
#line hidden
#nullable disable
            __builder.AddMarkupContent(37, "<div class=\"emptyListMessage\">There currently no challenges defined.</div>");
#nullable restore
#line 34 "D:\Code\GakuGym\public\src\Client\Pages\CategoryPage.razor"
		}

#line default
#line hidden
#nullable disable
            __builder.OpenElement(38, "div");
            __builder.AddAttribute(39, "class", "listHeader");
            __builder.AddMarkupContent(40, "<span>Facts</span>\n\t\t\t");
            __builder.OpenElement(41, "button");
            __builder.AddAttribute(42, "class", "SecondaryButton");
            __builder.AddAttribute(43, "onclick", Microsoft.AspNetCore.Components.EventCallback.Factory.Create<Microsoft.AspNetCore.Components.Web.MouseEventArgs>(this, 
#nullable restore
#line 37 "D:\Code\GakuGym\public\src\Client\Pages\CategoryPage.razor"
                                                      OnAddFactClick

#line default
#line hidden
#nullable disable
            ));
            __builder.AddMarkupContent(44, "<svg class=\"icon\"><use xlink:href=\"#add\"></use></svg>");
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.AddMarkupContent(45, "\n\t\t");
            __builder.OpenElement(46, "div");
            __builder.AddAttribute(47, "class", "searchWrapper");
            __builder.AddMarkupContent(48, "<input type=\"text\" placeholder=\"Enter a search query\">\n\t\t\t");
            __builder.OpenElement(49, "button");
            __builder.AddAttribute(50, "onclick", Microsoft.AspNetCore.Components.EventCallback.Factory.Create<Microsoft.AspNetCore.Components.Web.MouseEventArgs>(this, 
#nullable restore
#line 41 "D:\Code\GakuGym\public\src\Client\Pages\CategoryPage.razor"
                              OnSearchClick

#line default
#line hidden
#nullable disable
            ));
            __builder.AddMarkupContent(51, "<svg class=\"icon\"><use xlink:href=\"#search\"></use></svg>");
            __builder.CloseElement();
            __builder.CloseElement();
#nullable restore
#line 43 "D:\Code\GakuGym\public\src\Client\Pages\CategoryPage.razor"
         if(facts != null)
		{

#line default
#line hidden
#nullable disable
            __builder.OpenElement(52, "table");
            __builder.OpenElement(53, "thead");
            __builder.OpenElement(54, "tr");
            __builder.AddMarkupContent(55, "<th></th>");
#nullable restore
#line 49 "D:\Code\GakuGym\public\src\Client\Pages\CategoryPage.razor"
                         foreach(var field in category.fields)
						{

#line default
#line hidden
#nullable disable
            __builder.OpenElement(56, "th");
#nullable restore
#line (51,13)-(51,23) 25 "D:\Code\GakuGym\public\src\Client\Pages\CategoryPage.razor"
__builder.AddContent(57, field.name);

#line default
#line hidden
#nullable disable
            __builder.CloseElement();
#nullable restore
#line 52 "D:\Code\GakuGym\public\src\Client\Pages\CategoryPage.razor"
						}

#line default
#line hidden
#nullable disable
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.AddMarkupContent(58, "\n\t\t\t\t");
            __builder.OpenElement(59, "tbody");
#nullable restore
#line 56 "D:\Code\GakuGym\public\src\Client\Pages\CategoryPage.razor"
                     foreach(var fact in facts)
					{

#line default
#line hidden
#nullable disable
            __builder.OpenElement(60, "tr");
            __builder.OpenElement(61, "td");
            __builder.OpenElement(62, "button");
            __builder.AddAttribute(63, "class", "SecondaryButton");
            __builder.AddAttribute(64, "onclick", Microsoft.AspNetCore.Components.EventCallback.Factory.Create<Microsoft.AspNetCore.Components.Web.MouseEventArgs>(this, 
#nullable restore
#line 59 "D:\Code\GakuGym\public\src\Client\Pages\CategoryPage.razor"
                                                                          () => OnEditFact(fact.guid)

#line default
#line hidden
#nullable disable
            ));
            __builder.AddMarkupContent(65, "<svg class=\"icon\"><use xlink:href=\"#edit\"></use></svg>");
            __builder.CloseElement();
            __builder.CloseElement();
#nullable restore
#line 60 "D:\Code\GakuGym\public\src\Client\Pages\CategoryPage.razor"
                             foreach(var field in category.fields)
							{

#line default
#line hidden
#nullable disable
            __builder.OpenElement(66, "td");
            __builder.OpenElement(67, "pre");
#nullable restore
#line (63,16)-(63,42) 25 "D:\Code\GakuGym\public\src\Client\Pages\CategoryPage.razor"
__builder.AddContent(68, fact.fieldData[field.guid]);

#line default
#line hidden
#nullable disable
            __builder.CloseElement();
            __builder.CloseElement();
#nullable restore
#line 65 "D:\Code\GakuGym\public\src\Client\Pages\CategoryPage.razor"
							}

#line default
#line hidden
#nullable disable
            __builder.CloseElement();
#nullable restore
#line 67 "D:\Code\GakuGym\public\src\Client\Pages\CategoryPage.razor"
					}

#line default
#line hidden
#nullable disable
            __builder.CloseElement();
            __builder.CloseElement();
#nullable restore
#line 70 "D:\Code\GakuGym\public\src\Client\Pages\CategoryPage.razor"
		}

#line default
#line hidden
#nullable disable
            __builder.CloseElement();
#nullable restore
#line 72 "D:\Code\GakuGym\public\src\Client\Pages\CategoryPage.razor"
}

#line default
#line hidden
#nullable disable
        }
        #pragma warning restore 1998
#nullable restore
#line 75 "D:\Code\GakuGym\public\src\Client\Pages\CategoryPage.razor"
 
	[Parameter]
	public Guid RouteParamCategoryId { get; set; }

	Category?        category;
	List<Challenge>? challenges;
	List<Fact>?      facts;

	protected override async Task OnParametersSetAsync()
	{
		category = await API.GetCategory(RouteParamCategoryId);
		challenges = await API.GetChallengesByCategory(RouteParamCategoryId);
	}

	void OnEditFact(Guid factId)
	{
		NavigationManager.NavigateTo($"/fact-database/fact/{factId}/edit");
	}

	void OnBackClick()
	{
		NavigationManager.NavigateTo($"/fact-database/domain/{category.domainId}");
	}

	void OnEditClick()
	{
		NavigationManager.NavigateTo($"/fact-database/category/{RouteParamCategoryId}/edit");		
	}

	void OnEditChallenge(Challenge challenge)
	{
		NavigationManager.NavigateTo($"/fact-database/challenge/{challenge.id}/edit");		
	}

	void OnAddChallengeClick()
	{
		NavigationManager.NavigateTo($"/fact-database/category/{RouteParamCategoryId}/add-challenge");
	}

	void OnAddFactClick()
	{
		NavigationManager.NavigateTo($"/fact-database/category/{RouteParamCategoryId}/add-fact");
	}

	async Task OnSearchClick()
	{
		var results = await API.SearchFacts(new SearchQuery { categoryId = category.guid });

		facts = results.facts;
	}

#line default
#line hidden
#nullable disable
    }
}
#pragma warning restore 1591
