#pragma checksum "D:\Code\GakuGym\public\src\Client\Pages\Studies.razor" "{8829d00f-11b8-4213-878b-770e8597ac16}" "6c6e0a43ccf427a8b1542f447076987d78a76fb3dd77f0278536ae5b1cb37006"
// <auto-generated/>
#pragma warning disable 1591
namespace GakuGym.Client.Pages
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Components;
#nullable restore
#line 1 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using System.Net.Http;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using System.Net.Http.Json;

#line default
#line hidden
#nullable disable
#nullable restore
#line 3 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using Microsoft.AspNetCore.Components.Forms;

#line default
#line hidden
#nullable disable
#nullable restore
#line 4 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using Microsoft.AspNetCore.Components.Routing;

#line default
#line hidden
#nullable disable
#nullable restore
#line 5 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using Microsoft.AspNetCore.Components.Web;

#line default
#line hidden
#nullable disable
#nullable restore
#line 6 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using Microsoft.AspNetCore.Components.WebAssembly.Http;

#line default
#line hidden
#nullable disable
#nullable restore
#line 7 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using Microsoft.JSInterop;

#line default
#line hidden
#nullable disable
#nullable restore
#line 8 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using GakuGym.Client;

#line default
#line hidden
#nullable disable
#nullable restore
#line 9 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using GakuGym.Common;

#line default
#line hidden
#nullable disable
    [Microsoft.AspNetCore.Components.RouteAttribute("/studies")]
    public partial class Studies : BaseComponent
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.OpenElement(0, "div");
            __builder.AddAttribute(1, "id", "pageHeader");
            __builder.AddMarkupContent(2, "<span id=\"pageHeaderLeft\">Studies</span>\n    ");
            __builder.OpenElement(3, "span");
            __builder.AddAttribute(4, "id", "pageHeaderRight");
            __builder.OpenElement(5, "button");
            __builder.AddAttribute(6, "class", "SecondaryButton");
            __builder.AddAttribute(7, "onclick", Microsoft.AspNetCore.Components.EventCallback.Factory.Create<Microsoft.AspNetCore.Components.Web.MouseEventArgs>(this, 
#nullable restore
#line 6 "D:\Code\GakuGym\public\src\Client\Pages\Studies.razor"
                                                                         OnBackClick

#line default
#line hidden
#nullable disable
            ));
            __builder.AddMarkupContent(8, "<svg class=\"icon\"><use xlink:href=\"#back\"></use></svg>");
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.AddMarkupContent(9, "\n");
            __builder.OpenElement(10, "div");
            __builder.AddAttribute(11, "id", "pageBody");
            __builder.OpenElement(12, "div");
            __builder.AddAttribute(13, "class", "listHeader");
            __builder.AddMarkupContent(14, "<span>Studies</span>\n\t\t");
            __builder.OpenElement(15, "button");
            __builder.AddAttribute(16, "class", "SecondaryButton");
            __builder.AddAttribute(17, "onclick", Microsoft.AspNetCore.Components.EventCallback.Factory.Create<Microsoft.AspNetCore.Components.Web.MouseEventArgs>(this, 
#nullable restore
#line 11 "D:\Code\GakuGym\public\src\Client\Pages\Studies.razor"
                                                  OnAddStudyClick

#line default
#line hidden
#nullable disable
            ));
            __builder.AddMarkupContent(18, "<svg class=\"icon\"><use xlink:href=\"#add\"></use></svg>");
            __builder.CloseElement();
            __builder.CloseElement();
#nullable restore
#line 13 "D:\Code\GakuGym\public\src\Client\Pages\Studies.razor"
     if(studies != null)
    {
        

#line default
#line hidden
#nullable disable
#nullable restore
#line 15 "D:\Code\GakuGym\public\src\Client\Pages\Studies.razor"
         foreach(var study in studies)
        {

#line default
#line hidden
#nullable disable
            __builder.OpenElement(19, "div");
            __builder.AddAttribute(20, "class", "card");
            __builder.OpenElement(21, "div");
#nullable restore
#line (18,23)-(18,33) 25 "D:\Code\GakuGym\public\src\Client\Pages\Studies.razor"
__builder.AddContent(22, study.name);

#line default
#line hidden
#nullable disable
            __builder.CloseElement();
            __builder.AddMarkupContent(23, "\n                ");
            __builder.OpenElement(24, "button");
            __builder.AddAttribute(25, "onclick", Microsoft.AspNetCore.Components.EventCallback.Factory.Create<Microsoft.AspNetCore.Components.Web.MouseEventArgs>(this, 
#nullable restore
#line 19 "D:\Code\GakuGym\public\src\Client\Pages\Studies.razor"
                                  () => OnBeginStudyClick(study)

#line default
#line hidden
#nullable disable
            ));
            __builder.AddContent(26, "Begin Study");
            __builder.CloseElement();
            __builder.CloseElement();
#nullable restore
#line 21 "D:\Code\GakuGym\public\src\Client\Pages\Studies.razor"
        }

#line default
#line hidden
#nullable disable
#nullable restore
#line 21 "D:\Code\GakuGym\public\src\Client\Pages\Studies.razor"
         
    }

#line default
#line hidden
#nullable disable
            __builder.CloseElement();
        }
        #pragma warning restore 1998
#nullable restore
#line 25 "D:\Code\GakuGym\public\src\Client\Pages\Studies.razor"
 
    List<Study>? studies;

    void OnBackClick()
    {
        NavigationManager.NavigateTo("/");    
    }

    void OnBeginStudyClick(Study study)
    {
        NavigationManager.NavigateTo($"/study-session/{study.id}");
    }

    void OnAddStudyClick()
    {
        NavigationManager.NavigateTo("/studies/add-study");
    }

    protected override async Task OnParametersSetAsync()
    {
        studies = await API.GetStudies();
    }

#line default
#line hidden
#nullable disable
    }
}
#pragma warning restore 1591
