#pragma checksum "D:\Code\GakuGym\public\src\Client\Pages\NewDomain.razor" "{8829d00f-11b8-4213-878b-770e8597ac16}" "07711c27ae3b3b2bc995d225228fa8b58fab850ecee2e4708c6214ab1944e0bc"
// <auto-generated/>
#pragma warning disable 1591
namespace GakuGym.Client.Pages
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Components;
#nullable restore
#line 1 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using System.Net.Http;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using System.Net.Http.Json;

#line default
#line hidden
#nullable disable
#nullable restore
#line 3 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using Microsoft.AspNetCore.Components.Forms;

#line default
#line hidden
#nullable disable
#nullable restore
#line 4 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using Microsoft.AspNetCore.Components.Routing;

#line default
#line hidden
#nullable disable
#nullable restore
#line 5 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using Microsoft.AspNetCore.Components.Web;

#line default
#line hidden
#nullable disable
#nullable restore
#line 6 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using Microsoft.AspNetCore.Components.WebAssembly.Http;

#line default
#line hidden
#nullable disable
#nullable restore
#line 7 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using Microsoft.JSInterop;

#line default
#line hidden
#nullable disable
#nullable restore
#line 8 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using GakuGym.Client;

#line default
#line hidden
#nullable disable
#nullable restore
#line 9 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using GakuGym.Common;

#line default
#line hidden
#nullable disable
#nullable restore
#line 3 "D:\Code\GakuGym\public\src\Client\Pages\NewDomain.razor"
using System.ComponentModel.DataAnnotations;

#line default
#line hidden
#nullable disable
    [Microsoft.AspNetCore.Components.RouteAttribute("/fact-database/new-domain")]
    public partial class NewDomain : BaseComponent
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.OpenElement(0, "div");
            __builder.AddAttribute(1, "id", "pageHeader");
            __builder.AddMarkupContent(2, "<span id=\"pageHeaderLeft\">New Domain</span>\n    ");
            __builder.OpenElement(3, "span");
            __builder.AddAttribute(4, "id", "pageHeaderRight");
            __builder.OpenElement(5, "button");
            __builder.AddAttribute(6, "class", "SecondaryButton");
            __builder.AddAttribute(7, "onclick", Microsoft.AspNetCore.Components.EventCallback.Factory.Create<Microsoft.AspNetCore.Components.Web.MouseEventArgs>(this, 
#nullable restore
#line 7 "D:\Code\GakuGym\public\src\Client\Pages\NewDomain.razor"
                                                                         OnCloseClick

#line default
#line hidden
#nullable disable
            ));
            __builder.AddMarkupContent(8, "<svg class=\"icon\"><use xlink:href=\"#close\"></use></svg>");
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.AddMarkupContent(9, "\n");
            __builder.OpenElement(10, "div");
            __builder.AddAttribute(11, "id", "pageBody");
            __builder.OpenComponent<Microsoft.AspNetCore.Components.Forms.EditForm>(12);
            __builder.AddAttribute(13, "OnSubmit", global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<Microsoft.AspNetCore.Components.EventCallback<Microsoft.AspNetCore.Components.Forms.EditContext>>(Microsoft.AspNetCore.Components.EventCallback.Factory.Create<Microsoft.AspNetCore.Components.Forms.EditContext>(this, 
#nullable restore
#line 10 "D:\Code\GakuGym\public\src\Client\Pages\NewDomain.razor"
                        OnCreateClick

#line default
#line hidden
#nullable disable
            )));
            __builder.AddAttribute(14, "EditContext", global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<Microsoft.AspNetCore.Components.Forms.EditContext>(
#nullable restore
#line 10 "D:\Code\GakuGym\public\src\Client\Pages\NewDomain.razor"
                                                    editContext

#line default
#line hidden
#nullable disable
            ));
            __builder.AddAttribute(15, "ChildContent", (Microsoft.AspNetCore.Components.RenderFragment<Microsoft.AspNetCore.Components.Forms.EditContext>)((context) => (__builder2) => {
                __builder2.OpenComponent<Microsoft.AspNetCore.Components.Forms.DataAnnotationsValidator>(16);
                __builder2.CloseComponent();
                __builder2.AddMarkupContent(17, "\n\t\t");
                __builder2.OpenElement(18, "div");
                __builder2.AddAttribute(19, "class", "inputWrapper");
                __builder2.AddMarkupContent(20, "<label>Name</label>\n\t\t\t");
                __builder2.OpenComponent<Microsoft.AspNetCore.Components.Forms.InputText>(21);
                __builder2.AddAttribute(22, "placeholder", "Name of the domain");
                __builder2.AddAttribute(23, "Value", global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<System.String>(
#nullable restore
#line 14 "D:\Code\GakuGym\public\src\Client\Pages\NewDomain.razor"
                                    this.nameText

#line default
#line hidden
#nullable disable
                ));
                __builder2.AddAttribute(24, "ValueChanged", global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<Microsoft.AspNetCore.Components.EventCallback<System.String>>(Microsoft.AspNetCore.Components.EventCallback.Factory.Create<System.String>(this, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.CreateInferredEventCallback(this, __value => this.nameText = __value, this.nameText))));
                __builder2.AddAttribute(25, "ValueExpression", global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<System.Linq.Expressions.Expression<System.Func<System.String>>>(() => this.nameText));
                __builder2.CloseComponent();
                __builder2.AddMarkupContent(26, "\n\t\t\t");
                __Blazor.GakuGym.Client.Pages.NewDomain.TypeInference.CreateValidationMessage_0(__builder2, 27, 28, 
#nullable restore
#line 15 "D:\Code\GakuGym\public\src\Client\Pages\NewDomain.razor"
                                    () => this.nameText

#line default
#line hidden
#nullable disable
                );
                __builder2.CloseElement();
                __builder2.AddMarkupContent(29, "\n\t\t");
                __builder2.OpenElement(30, "div");
                __builder2.AddAttribute(31, "class", "inputWrapper");
                __builder2.AddMarkupContent(32, "<label>Description</label>\n\t\t\t");
                __builder2.OpenComponent<Microsoft.AspNetCore.Components.Forms.InputText>(33);
                __builder2.AddAttribute(34, "placeholder", "A description (optional)");
                __builder2.AddAttribute(35, "Value", global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<System.String>(
#nullable restore
#line 19 "D:\Code\GakuGym\public\src\Client\Pages\NewDomain.razor"
                                    this.descriptionText

#line default
#line hidden
#nullable disable
                ));
                __builder2.AddAttribute(36, "ValueChanged", global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<Microsoft.AspNetCore.Components.EventCallback<System.String>>(Microsoft.AspNetCore.Components.EventCallback.Factory.Create<System.String>(this, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.CreateInferredEventCallback(this, __value => this.descriptionText = __value, this.descriptionText))));
                __builder2.AddAttribute(37, "ValueExpression", global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<System.Linq.Expressions.Expression<System.Func<System.String>>>(() => this.descriptionText));
                __builder2.CloseComponent();
                __builder2.CloseElement();
                __builder2.AddMarkupContent(38, "\n\t\t");
                __builder2.AddMarkupContent(39, "<button type=\"submit\">Create</button>");
            }
            ));
            __builder.CloseComponent();
            __builder.CloseElement();
        }
        #pragma warning restore 1998
#nullable restore
#line 26 "D:\Code\GakuGym\public\src\Client\Pages\NewDomain.razor"
 
	EditContext editContext { get; set; }

	[Required]
	public string? nameText { get; set; }
	string? descriptionText;

	void OnCloseClick()
	{
		NavigationManager.NavigateTo("/fact-database");
	}

	protected override void OnInitialized()
	{
		editContext = new EditContext(this);
	}

	async Task OnCreateClick()
	{
		if(editContext.Validate())
		{
			await API.CreateDomain(nameText, descriptionText);

			NavigationManager.NavigateTo("/fact-database");			
		}
	}

#line default
#line hidden
#nullable disable
    }
}
namespace __Blazor.GakuGym.Client.Pages.NewDomain
{
    #line hidden
    internal static class TypeInference
    {
        public static void CreateValidationMessage_0<TValue>(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder, int seq, int __seq0, global::System.Linq.Expressions.Expression<global::System.Func<TValue>> __arg0)
        {
        __builder.OpenComponent<global::Microsoft.AspNetCore.Components.Forms.ValidationMessage<TValue>>(seq);
        __builder.AddAttribute(__seq0, "For", __arg0);
        __builder.CloseComponent();
        }
    }
}
#pragma warning restore 1591
