#pragma checksum "D:\code\StudyGym\StudyGym6\Client\Shared\BlankLayout.razor" "{8829d00f-11b8-4213-878b-770e8597ac16}" "1cdfd95c314311ff969dd401b6a90120dc8e3365eb4f2995e8331acd2f085213"
// <auto-generated/>
#pragma warning disable 1591
namespace StudyGym.Client.Shared
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Components;
#nullable restore
#line 1 "D:\code\StudyGym\StudyGym6\Client\_Imports.razor"
using System.Net.Http;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "D:\code\StudyGym\StudyGym6\Client\_Imports.razor"
using System.Net.Http.Json;

#line default
#line hidden
#nullable disable
#nullable restore
#line 3 "D:\code\StudyGym\StudyGym6\Client\_Imports.razor"
using Microsoft.AspNetCore.Components.Forms;

#line default
#line hidden
#nullable disable
#nullable restore
#line 4 "D:\code\StudyGym\StudyGym6\Client\_Imports.razor"
using Microsoft.AspNetCore.Components.Routing;

#line default
#line hidden
#nullable disable
#nullable restore
#line 5 "D:\code\StudyGym\StudyGym6\Client\_Imports.razor"
using Microsoft.AspNetCore.Components.Web;

#line default
#line hidden
#nullable disable
#nullable restore
#line 6 "D:\code\StudyGym\StudyGym6\Client\_Imports.razor"
using Microsoft.AspNetCore.Components.WebAssembly.Http;

#line default
#line hidden
#nullable disable
#nullable restore
#line 7 "D:\code\StudyGym\StudyGym6\Client\_Imports.razor"
using Microsoft.JSInterop;

#line default
#line hidden
#nullable disable
#nullable restore
#line 8 "D:\code\StudyGym\StudyGym6\Client\_Imports.razor"
using StudyGym.Client;

#line default
#line hidden
#nullable disable
#nullable restore
#line 9 "D:\code\StudyGym\StudyGym6\Client\_Imports.razor"
using StudyGym.Client.Shared;

#line default
#line hidden
#nullable disable
#nullable restore
#line 10 "D:\code\StudyGym\StudyGym6\Client\_Imports.razor"
using StudyGym.Core;

#line default
#line hidden
#nullable disable
    public partial class BlankLayout : LayoutComponentBase
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.OpenElement(0, "div");
            __builder.AddAttribute(1, "id", "blankLayoutContainer");
#nullable restore
#line (4,6)-(4,10) 24 "D:\code\StudyGym\StudyGym6\Client\Shared\BlankLayout.razor"
__builder.AddContent(2, Body);

#line default
#line hidden
#nullable disable
            __builder.CloseElement();
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
