#pragma checksum "D:\Code\GakuGym\public\src\Client\UI\Pages\AddStudy.razor" "{8829d00f-11b8-4213-878b-770e8597ac16}" "31cc60e4383c5b7151f1950800b0065e44f921e35cc9c64dcf499437d320d53e"
// <auto-generated/>
#pragma warning disable 1591
namespace GakuGym.Client.UI.Pages
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Components;
#nullable restore
#line 1 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using System.Net.Http;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using System.Net.Http.Json;

#line default
#line hidden
#nullable disable
#nullable restore
#line 3 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using Microsoft.AspNetCore.Components.Forms;

#line default
#line hidden
#nullable disable
#nullable restore
#line 4 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using Microsoft.AspNetCore.Components.Routing;

#line default
#line hidden
#nullable disable
#nullable restore
#line 5 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using Microsoft.AspNetCore.Components.Web;

#line default
#line hidden
#nullable disable
#nullable restore
#line 6 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using Microsoft.AspNetCore.Components.WebAssembly.Http;

#line default
#line hidden
#nullable disable
#nullable restore
#line 7 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using Microsoft.JSInterop;

#line default
#line hidden
#nullable disable
#nullable restore
#line 8 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using GakuGym.Client;

#line default
#line hidden
#nullable disable
#nullable restore
#line 9 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using GakuGym.Common;

#line default
#line hidden
#nullable disable
    [Microsoft.AspNetCore.Components.RouteAttribute("/studies/add-study")]
    public partial class AddStudy : BaseComponent
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.OpenElement(0, "div");
            __builder.AddAttribute(1, "id", "pageHeader");
            __builder.AddMarkupContent(2, "<span id=\"pageHeaderLeft\">New Study</span>\n\t");
            __builder.OpenElement(3, "span");
            __builder.AddAttribute(4, "id", "pageHeaderRight");
            __builder.OpenElement(5, "button");
            __builder.AddAttribute(6, "class", "SecondaryButton");
            __builder.AddAttribute(7, "onclick", Microsoft.AspNetCore.Components.EventCallback.Factory.Create<Microsoft.AspNetCore.Components.Web.MouseEventArgs>(this, 
#nullable restore
#line 7 "D:\Code\GakuGym\public\src\Client\UI\Pages\AddStudy.razor"
                                                  OnCloseClick

#line default
#line hidden
#nullable disable
            ));
            __builder.AddMarkupContent(8, "<svg class=\"icon\"><use xlink:href=\"#close\"></use></svg>");
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.AddMarkupContent(9, "\n");
            __builder.OpenElement(10, "div");
            __builder.AddAttribute(11, "id", "pageBody");
            __builder.OpenElement(12, "div");
            __builder.AddAttribute(13, "class", "inputWrapper");
            __builder.AddMarkupContent(14, "<label>Name</label>\n        ");
            __builder.OpenElement(15, "input");
            __builder.AddAttribute(16, "type", "text");
            __builder.AddAttribute(17, "value", Microsoft.AspNetCore.Components.BindConverter.FormatValue(
#nullable restore
#line 14 "D:\Code\GakuGym\public\src\Client\UI\Pages\AddStudy.razor"
                                        studyNameText

#line default
#line hidden
#nullable disable
            ));
            __builder.AddAttribute(18, "onchange", Microsoft.AspNetCore.Components.EventCallback.Factory.CreateBinder(this, __value => studyNameText = __value, studyNameText));
            __builder.SetUpdatesAttributeName("value");
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.AddMarkupContent(19, "\n\t");
            __builder.OpenElement(20, "div");
            __builder.AddAttribute(21, "class", "listHeader");
            __builder.AddMarkupContent(22, "<span>Fact Groups</span>\n\t\t");
            __builder.OpenElement(23, "button");
            __builder.AddAttribute(24, "class", "SecondaryButton");
            __builder.AddAttribute(25, "onclick", Microsoft.AspNetCore.Components.EventCallback.Factory.Create<Microsoft.AspNetCore.Components.Web.MouseEventArgs>(this, 
#nullable restore
#line 18 "D:\Code\GakuGym\public\src\Client\UI\Pages\AddStudy.razor"
                                                  OnAddFactGroupClick

#line default
#line hidden
#nullable disable
            ));
            __builder.AddMarkupContent(26, "<svg class=\"icon\"><use xlink:href=\"#add\"></use></svg>");
            __builder.CloseElement();
            __builder.CloseElement();
#nullable restore
#line 20 "D:\Code\GakuGym\public\src\Client\UI\Pages\AddStudy.razor"
     foreach(var factGroup in factGroups)
    {

#line default
#line hidden
#nullable disable
            __builder.OpenElement(27, "div");
            __builder.OpenElement(28, "div");
            __builder.AddAttribute(29, "class", "inputWrapper");
            __builder.AddMarkupContent(30, "<label>Domain</label>\n                ");
            __builder.OpenElement(31, "select");
            __builder.AddAttribute(32, "value", 
#nullable restore
#line 25 "D:\Code\GakuGym\public\src\Client\UI\Pages\AddStudy.razor"
                                factGroup.domain?.guid

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(33, "onchange", Microsoft.AspNetCore.Components.EventCallback.Factory.Create<Microsoft.AspNetCore.Components.ChangeEventArgs>(this, 
#nullable restore
#line 25 "D:\Code\GakuGym\public\src\Client\UI\Pages\AddStudy.razor"
                                                                   e => OnFactGroupDomainChange(factGroup, (string?)e.Value)

#line default
#line hidden
#nullable disable
            ));
            __builder.OpenElement(34, "option");
            __builder.CloseElement();
#nullable restore
#line 27 "D:\Code\GakuGym\public\src\Client\UI\Pages\AddStudy.razor"
                     foreach(var domain in domains)
                    {

#line default
#line hidden
#nullable disable
            __builder.OpenElement(35, "option");
            __builder.AddAttribute(36, "value", 
#nullable restore
#line 29 "D:\Code\GakuGym\public\src\Client\UI\Pages\AddStudy.razor"
                                        domain.guid

#line default
#line hidden
#nullable disable
            );
#nullable restore
#line (29,55)-(29,66) 25 "D:\Code\GakuGym\public\src\Client\UI\Pages\AddStudy.razor"
__builder.AddContent(37, domain.name);

#line default
#line hidden
#nullable disable
            __builder.CloseElement();
#nullable restore
#line 30 "D:\Code\GakuGym\public\src\Client\UI\Pages\AddStudy.razor"
                    }

#line default
#line hidden
#nullable disable
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.AddMarkupContent(38, "\n            ");
            __builder.OpenElement(39, "div");
            __builder.AddAttribute(40, "class", "inputWrapper");
            __builder.AddMarkupContent(41, "<label>Category</label>\n                ");
            __builder.OpenElement(42, "select");
            __builder.AddAttribute(43, "value", 
#nullable restore
#line 35 "D:\Code\GakuGym\public\src\Client\UI\Pages\AddStudy.razor"
                                factGroup.category?.guid

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(44, "onchange", Microsoft.AspNetCore.Components.EventCallback.Factory.Create<Microsoft.AspNetCore.Components.ChangeEventArgs>(this, 
#nullable restore
#line 35 "D:\Code\GakuGym\public\src\Client\UI\Pages\AddStudy.razor"
                                                                     e => OnFactGroupCategoryChange(factGroup, (string?)e.Value)

#line default
#line hidden
#nullable disable
            ));
            __builder.OpenElement(45, "option");
            __builder.CloseElement();
#nullable restore
#line 37 "D:\Code\GakuGym\public\src\Client\UI\Pages\AddStudy.razor"
                     foreach(var category in categories.Where(x => factGroup.domain != null && x.domainId == factGroup.domain.guid))
                    {

#line default
#line hidden
#nullable disable
            __builder.OpenElement(46, "option");
            __builder.AddAttribute(47, "value", 
#nullable restore
#line 39 "D:\Code\GakuGym\public\src\Client\UI\Pages\AddStudy.razor"
                                        category.guid

#line default
#line hidden
#nullable disable
            );
#nullable restore
#line (39,57)-(39,70) 25 "D:\Code\GakuGym\public\src\Client\UI\Pages\AddStudy.razor"
__builder.AddContent(48, category.name);

#line default
#line hidden
#nullable disable
            __builder.CloseElement();
#nullable restore
#line 40 "D:\Code\GakuGym\public\src\Client\UI\Pages\AddStudy.razor"
                    }

#line default
#line hidden
#nullable disable
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.CloseElement();
#nullable restore
#line 44 "D:\Code\GakuGym\public\src\Client\UI\Pages\AddStudy.razor"
    }

#line default
#line hidden
#nullable disable
            __builder.OpenElement(49, "button");
            __builder.AddAttribute(50, "onclick", Microsoft.AspNetCore.Components.EventCallback.Factory.Create<Microsoft.AspNetCore.Components.Web.MouseEventArgs>(this, 
#nullable restore
#line 45 "D:\Code\GakuGym\public\src\Client\UI\Pages\AddStudy.razor"
                      OnAddStudyButtonClick

#line default
#line hidden
#nullable disable
            ));
            __builder.AddContent(51, "Add Study");
            __builder.CloseElement();
            __builder.CloseElement();
        }
        #pragma warning restore 1998
#nullable restore
#line 49 "D:\Code\GakuGym\public\src\Client\UI\Pages\AddStudy.razor"
 
    class FactGroup
    {
        public Domain?   domain;
        public Category? category;
        public int       newChallengesPerInterval;
        public int       newIntervalMinutes;
        public string?   schedulingAlgorithm;
    }

    string? studyNameText;
    List<Category>  categories = new List<Category>();
    List<Domain>    domains    = new List<Domain>();
    List<FactGroup> factGroups = new List<FactGroup>();

    void OnCloseClick()
    {
        NavigationManager.NavigateTo("/studies");
    }

    void OnAddFactGroupClick()
    {
        factGroups.Add(new FactGroup { });    
    }

    async Task OnAddStudyButtonClick()
    {
        await API.SaveStudy(new Study
        {
            name = studyNameText,
            factGroups = factGroups.Select(x => new StudyFactGroup
            {                
                categoryId = x.category.guid                
            }).ToList()
        });

        NavigationManager.NavigateTo("/studies");
    }

    void OnFactGroupDomainChange(FactGroup factGroup, string? domainId)
    {
        if(domainId == null)
        { 
            factGroup.domain = null;
            return;
        }

        factGroup.domain = domains.First(x => x.guid == Guid.Parse(domainId));
    }

    void OnFactGroupCategoryChange(FactGroup factGroup, string? categoryId)
    {
        if(categoryId == null)
        {
            factGroup.category = null;
            return;
        }

        factGroup.category = categories.First(x => x.guid == Guid.Parse(categoryId));
    }

    protected override async Task OnParametersSetAsync()
    {
        domains    = await API.GetDomains();
        categories = await API.GetAllCategories();
    }

#line default
#line hidden
#nullable disable
    }
}
#pragma warning restore 1591
