#pragma checksum "D:\Code\GakuGym\public\src\Client\UI\Pages\EditChallenge.razor" "{8829d00f-11b8-4213-878b-770e8597ac16}" "688d7e69776bbf4335a05c74581e69222bd3313f161e0753bec1db427ef8fcfc"
// <auto-generated/>
#pragma warning disable 1591
namespace GakuGym.Client.UI.Pages
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Components;
#nullable restore
#line 1 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using System.Net.Http;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using System.Net.Http.Json;

#line default
#line hidden
#nullable disable
#nullable restore
#line 3 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using Microsoft.AspNetCore.Components.Forms;

#line default
#line hidden
#nullable disable
#nullable restore
#line 4 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using Microsoft.AspNetCore.Components.Routing;

#line default
#line hidden
#nullable disable
#nullable restore
#line 5 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using Microsoft.AspNetCore.Components.Web;

#line default
#line hidden
#nullable disable
#nullable restore
#line 6 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using Microsoft.AspNetCore.Components.WebAssembly.Http;

#line default
#line hidden
#nullable disable
#nullable restore
#line 7 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using Microsoft.JSInterop;

#line default
#line hidden
#nullable disable
#nullable restore
#line 8 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using GakuGym.Client;

#line default
#line hidden
#nullable disable
#nullable restore
#line 9 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using GakuGym.Common;

#line default
#line hidden
#nullable disable
    [Microsoft.AspNetCore.Components.RouteAttribute("/fact-database/challenge/{RouteParamChallengeId:guid}/edit")]
    public partial class EditChallenge : BaseComponent
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
#nullable restore
#line 4 "D:\Code\GakuGym\public\src\Client\UI\Pages\EditChallenge.razor"
 if(challenge != null)
{

#line default
#line hidden
#nullable disable
            __builder.OpenElement(0, "div");
            __builder.AddAttribute(1, "id", "pageHeader");
            __builder.OpenElement(2, "span");
            __builder.AddAttribute(3, "id", "pageHeaderLeft");
            __builder.AddContent(4, "Edit Challenge - ");
#nullable restore
#line (7,50)-(7,64) 24 "D:\Code\GakuGym\public\src\Client\UI\Pages\EditChallenge.razor"
__builder.AddContent(5, challenge.name);

#line default
#line hidden
#nullable disable
            __builder.CloseElement();
            __builder.AddMarkupContent(6, "\n\t    ");
            __builder.OpenElement(7, "span");
            __builder.AddAttribute(8, "id", "pageHeaderRight");
            __builder.OpenElement(9, "button");
            __builder.AddAttribute(10, "class", "SecondaryButton");
            __builder.AddAttribute(11, "onclick", Microsoft.AspNetCore.Components.EventCallback.Factory.Create<Microsoft.AspNetCore.Components.Web.MouseEventArgs>(this, 
#nullable restore
#line 8 "D:\Code\GakuGym\public\src\Client\UI\Pages\EditChallenge.razor"
                                                                             OnCloseClick

#line default
#line hidden
#nullable disable
            ));
            __builder.AddMarkupContent(12, "<svg class=\"icon\"><use xlink:href=\"#close\"></use></svg>");
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.AddMarkupContent(13, "\n    ");
            __builder.OpenElement(14, "div");
            __builder.AddAttribute(15, "id", "pageBody");
            __builder.OpenElement(16, "div");
            __builder.AddAttribute(17, "class", "inputWrapper");
            __builder.AddMarkupContent(18, "<label>Name</label>\n        ");
            __builder.OpenElement(19, "input");
            __builder.AddAttribute(20, "type", "text");
            __builder.AddAttribute(21, "value", Microsoft.AspNetCore.Components.BindConverter.FormatValue(
#nullable restore
#line 13 "D:\Code\GakuGym\public\src\Client\UI\Pages\EditChallenge.razor"
                                        nameText

#line default
#line hidden
#nullable disable
            ));
            __builder.AddAttribute(22, "onchange", Microsoft.AspNetCore.Components.EventCallback.Factory.CreateBinder(this, __value => nameText = __value, nameText));
            __builder.SetUpdatesAttributeName("value");
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.AddMarkupContent(23, "\n        ");
            __builder.OpenElement(24, "div");
            __builder.AddAttribute(25, "class", "inputWrapper");
            __builder.AddMarkupContent(26, "<label>Front Template</label>\n        ");
            __builder.OpenElement(27, "textarea");
            __builder.AddAttribute(28, "value", Microsoft.AspNetCore.Components.BindConverter.FormatValue(
#nullable restore
#line 17 "D:\Code\GakuGym\public\src\Client\UI\Pages\EditChallenge.razor"
                         frontTemplateText

#line default
#line hidden
#nullable disable
            ));
            __builder.AddAttribute(29, "onchange", Microsoft.AspNetCore.Components.EventCallback.Factory.CreateBinder(this, __value => frontTemplateText = __value, frontTemplateText));
            __builder.SetUpdatesAttributeName("value");
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.AddMarkupContent(30, "\n        ");
            __builder.OpenElement(31, "div");
            __builder.AddAttribute(32, "class", "inputWrapper");
            __builder.AddMarkupContent(33, "<label>Back Template</label>\n        ");
            __builder.OpenElement(34, "textarea");
            __builder.AddAttribute(35, "value", Microsoft.AspNetCore.Components.BindConverter.FormatValue(
#nullable restore
#line 21 "D:\Code\GakuGym\public\src\Client\UI\Pages\EditChallenge.razor"
                         backTemplateText

#line default
#line hidden
#nullable disable
            ));
            __builder.AddAttribute(36, "onchange", Microsoft.AspNetCore.Components.EventCallback.Factory.CreateBinder(this, __value => backTemplateText = __value, backTemplateText));
            __builder.SetUpdatesAttributeName("value");
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.AddMarkupContent(37, "\n        ");
            __builder.OpenElement(38, "button");
            __builder.AddAttribute(39, "onclick", Microsoft.AspNetCore.Components.EventCallback.Factory.Create<Microsoft.AspNetCore.Components.Web.MouseEventArgs>(this, 
#nullable restore
#line 23 "D:\Code\GakuGym\public\src\Client\UI\Pages\EditChallenge.razor"
                          OnSaveClick

#line default
#line hidden
#nullable disable
            ));
            __builder.AddContent(40, "Save");
            __builder.CloseElement();
            __builder.CloseElement();
#nullable restore
#line 25 "D:\Code\GakuGym\public\src\Client\UI\Pages\EditChallenge.razor"
}

#line default
#line hidden
#nullable disable
        }
        #pragma warning restore 1998
#nullable restore
#line 28 "D:\Code\GakuGym\public\src\Client\UI\Pages\EditChallenge.razor"
 
    [Parameter]
    public Guid RouteParamChallengeId { get; set; }

    Challenge? challenge;

    string? nameText;
    string? frontTemplateText;
    string? backTemplateText;

    protected override async Task OnParametersSetAsync()
    {
        challenge = await API.GetChallenge(RouteParamChallengeId);

        nameText          = challenge.name;
        frontTemplateText = challenge.frontTemplate;
        backTemplateText  = challenge.backTemplate;
    }    

    void OnCloseClick()
    {
        NavigationManager.NavigateTo($"/fact-database/category/{challenge.categoryId}");
    }

    async Task OnSaveClick()
    {
        await API.SaveChallenge(new Challenge
        {
            id            = challenge.id,
            name          = nameText,
            frontTemplate = frontTemplateText,
            backTemplate  = backTemplateText,
            categoryId    = challenge.categoryId
        });

        NavigationManager.NavigateTo($"/fact-database/category/{challenge.categoryId}");
    }

#line default
#line hidden
#nullable disable
    }
}
#pragma warning restore 1591
