#pragma checksum "D:\Code\GakuGym\public\src\Client\UI\Pages\EditCategory.razor" "{8829d00f-11b8-4213-878b-770e8597ac16}" "a40094dc2413cd912f7253dca8223ad618fdd0d81d43395f665958e9b5835072"
// <auto-generated/>
#pragma warning disable 1591
namespace GakuGym.Client.UI.Pages
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Components;
#nullable restore
#line 1 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using System.Net.Http;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using System.Net.Http.Json;

#line default
#line hidden
#nullable disable
#nullable restore
#line 3 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using Microsoft.AspNetCore.Components.Forms;

#line default
#line hidden
#nullable disable
#nullable restore
#line 4 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using Microsoft.AspNetCore.Components.Routing;

#line default
#line hidden
#nullable disable
#nullable restore
#line 5 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using Microsoft.AspNetCore.Components.Web;

#line default
#line hidden
#nullable disable
#nullable restore
#line 6 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using Microsoft.AspNetCore.Components.WebAssembly.Http;

#line default
#line hidden
#nullable disable
#nullable restore
#line 7 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using Microsoft.JSInterop;

#line default
#line hidden
#nullable disable
#nullable restore
#line 8 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using GakuGym.Client;

#line default
#line hidden
#nullable disable
#nullable restore
#line 9 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using GakuGym.Common;

#line default
#line hidden
#nullable disable
    [Microsoft.AspNetCore.Components.RouteAttribute("/fact-database/category/{RouteCategoryId:guid}/edit")]
    public partial class EditCategory : BaseComponent
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
#nullable restore
#line 4 "D:\Code\GakuGym\public\src\Client\UI\Pages\EditCategory.razor"
 if(category != null)
{

#line default
#line hidden
#nullable disable
            __builder.OpenElement(0, "div");
            __builder.AddAttribute(1, "id", "pageHeader");
            __builder.OpenElement(2, "span");
            __builder.AddAttribute(3, "id", "pageHeaderLeft");
            __builder.AddContent(4, "Edit Category - ");
#nullable restore
#line (7,46)-(7,59) 24 "D:\Code\GakuGym\public\src\Client\UI\Pages\EditCategory.razor"
__builder.AddContent(5, category.name);

#line default
#line hidden
#nullable disable
            __builder.CloseElement();
            __builder.AddMarkupContent(6, "\n\t\t");
            __builder.OpenElement(7, "span");
            __builder.AddAttribute(8, "id", "pageHeaderRight");
            __builder.OpenElement(9, "button");
            __builder.AddAttribute(10, "class", "SecondaryButton");
            __builder.AddAttribute(11, "onclick", Microsoft.AspNetCore.Components.EventCallback.Factory.Create<Microsoft.AspNetCore.Components.Web.MouseEventArgs>(this, 
#nullable restore
#line 8 "D:\Code\GakuGym\public\src\Client\UI\Pages\EditCategory.razor"
                                                                             OnCloseClick

#line default
#line hidden
#nullable disable
            ));
            __builder.AddMarkupContent(12, "<svg class=\"icon\"><use xlink:href=\"#close\"></use></svg>");
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.AddMarkupContent(13, "\n\t");
            __builder.OpenElement(14, "div");
            __builder.AddAttribute(15, "id", "pageBody");
            __builder.OpenElement(16, "div");
            __builder.AddAttribute(17, "class", "inputWrapper");
            __builder.AddMarkupContent(18, "<label>Name</label>\n\t\t\t");
            __builder.OpenElement(19, "input");
            __builder.AddAttribute(20, "type", "text");
            __builder.AddAttribute(21, "value", Microsoft.AspNetCore.Components.BindConverter.FormatValue(
#nullable restore
#line 14 "D:\Code\GakuGym\public\src\Client\UI\Pages\EditCategory.razor"
                                            categoryNameText

#line default
#line hidden
#nullable disable
            ));
            __builder.AddAttribute(22, "onchange", Microsoft.AspNetCore.Components.EventCallback.Factory.CreateBinder(this, __value => categoryNameText = __value, categoryNameText));
            __builder.SetUpdatesAttributeName("value");
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.AddMarkupContent(23, "\n\t\t");
            __builder.OpenElement(24, "div");
            __builder.AddAttribute(25, "class", "inputWrapper");
            __builder.AddMarkupContent(26, "<label>Description</label>\n\t\t\t");
            __builder.OpenElement(27, "input");
            __builder.AddAttribute(28, "type", "text");
            __builder.AddAttribute(29, "value", Microsoft.AspNetCore.Components.BindConverter.FormatValue(
#nullable restore
#line 18 "D:\Code\GakuGym\public\src\Client\UI\Pages\EditCategory.razor"
                                            categoryDescriptionText

#line default
#line hidden
#nullable disable
            ));
            __builder.AddAttribute(30, "onchange", Microsoft.AspNetCore.Components.EventCallback.Factory.CreateBinder(this, __value => categoryDescriptionText = __value, categoryDescriptionText));
            __builder.SetUpdatesAttributeName("value");
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.AddMarkupContent(31, "\n\t\t");
            __builder.OpenElement(32, "div");
            __builder.AddAttribute(33, "class", "listHeader");
            __builder.AddMarkupContent(34, "<span>Fields</span>\n\t\t\t");
            __builder.OpenElement(35, "button");
            __builder.AddAttribute(36, "class", "SecondaryButton");
            __builder.AddAttribute(37, "onclick", Microsoft.AspNetCore.Components.EventCallback.Factory.Create<Microsoft.AspNetCore.Components.Web.MouseEventArgs>(this, 
#nullable restore
#line 22 "D:\Code\GakuGym\public\src\Client\UI\Pages\EditCategory.razor"
                                                      OnAddFieldClick

#line default
#line hidden
#nullable disable
            ));
            __builder.AddMarkupContent(38, "<svg class=\"icon\"><use xlink:href=\"#add\"></use></svg>");
            __builder.CloseElement();
            __builder.CloseElement();
#nullable restore
#line 25 "D:\Code\GakuGym\public\src\Client\UI\Pages\EditCategory.razor"
         foreach(var field in fields)
		{

#line default
#line hidden
#nullable disable
            __builder.OpenElement(39, "div");
            __builder.OpenElement(40, "div");
            __builder.AddAttribute(41, "class", "inputWrapper");
            __builder.AddMarkupContent(42, "<label>Name</label> \n\t\t\t\t\t");
            __builder.OpenElement(43, "input");
            __builder.AddAttribute(44, "type", "text");
            __builder.AddAttribute(45, "value", Microsoft.AspNetCore.Components.BindConverter.FormatValue(
#nullable restore
#line 30 "D:\Code\GakuGym\public\src\Client\UI\Pages\EditCategory.razor"
                                                    field.name

#line default
#line hidden
#nullable disable
            ));
            __builder.AddAttribute(46, "onchange", Microsoft.AspNetCore.Components.EventCallback.Factory.CreateBinder(this, __value => field.name = __value, field.name));
            __builder.SetUpdatesAttributeName("value");
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.AddMarkupContent(47, "\n\t\t\t\t");
            __builder.OpenElement(48, "div");
            __builder.AddAttribute(49, "class", "inputWrapper");
            __builder.OpenElement(50, "input");
            __builder.AddAttribute(51, "type", "text");
            __builder.AddAttribute(52, "value", Microsoft.AspNetCore.Components.BindConverter.FormatValue(
#nullable restore
#line 33 "D:\Code\GakuGym\public\src\Client\UI\Pages\EditCategory.razor"
                                                    field.description

#line default
#line hidden
#nullable disable
            ));
            __builder.AddAttribute(53, "onchange", Microsoft.AspNetCore.Components.EventCallback.Factory.CreateBinder(this, __value => field.description = __value, field.description));
            __builder.SetUpdatesAttributeName("value");
            __builder.CloseElement();
            __builder.AddMarkupContent(54, "\n\t\t\t\t\t");
            __builder.AddMarkupContent(55, "<label>Description</label>");
            __builder.CloseElement();
            __builder.AddMarkupContent(56, "\n\t\t\t\t");
            __builder.OpenElement(57, "div");
            __builder.AddAttribute(58, "class", "inputWrapper");
            __builder.OpenElement(59, "select");
            __builder.AddAttribute(60, "value", Microsoft.AspNetCore.Components.BindConverter.FormatValue(
#nullable restore
#line 37 "D:\Code\GakuGym\public\src\Client\UI\Pages\EditCategory.razor"
                                   field.interpretation

#line default
#line hidden
#nullable disable
            ));
            __builder.AddAttribute(61, "onchange", Microsoft.AspNetCore.Components.EventCallback.Factory.CreateBinder(this, __value => field.interpretation = __value, field.interpretation));
            __builder.SetUpdatesAttributeName("value");
            __builder.OpenElement(62, "option");
            __builder.AddAttribute(63, "value", "Text");
            __builder.AddContent(64, "Text");
            __builder.CloseElement();
            __builder.AddMarkupContent(65, "\n\t\t\t\t\t\t");
            __builder.OpenElement(66, "option");
            __builder.AddAttribute(67, "value", "HTML");
            __builder.AddContent(68, "HTML");
            __builder.CloseElement();
            __builder.AddMarkupContent(69, "\n\t\t\t\t\t\t");
            __builder.OpenElement(70, "option");
            __builder.AddAttribute(71, "value", "Image");
            __builder.AddContent(72, "Image");
            __builder.CloseElement();
            __builder.AddMarkupContent(73, "\n\t\t\t\t\t\t");
            __builder.OpenElement(74, "option");
            __builder.AddAttribute(75, "value", "Audio");
            __builder.AddContent(76, "Audio");
            __builder.CloseElement();
            __builder.AddMarkupContent(77, "\n\t\t\t\t\t\t");
            __builder.OpenElement(78, "option");
            __builder.AddAttribute(79, "value", "Numeric");
            __builder.AddContent(80, "Numeric");
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.AddMarkupContent(81, "\n\t\t\t\t\t");
            __builder.AddMarkupContent(82, "<label>Interpretation</label>");
            __builder.CloseElement();
            __builder.AddMarkupContent(83, "\n\t\t\t\t");
            __builder.OpenElement(84, "button");
            __builder.AddAttribute(85, "onclick", Microsoft.AspNetCore.Components.EventCallback.Factory.Create<Microsoft.AspNetCore.Components.Web.MouseEventArgs>(this, 
#nullable restore
#line 46 "D:\Code\GakuGym\public\src\Client\UI\Pages\EditCategory.razor"
                                  () => OnRemoveFieldClick(field)

#line default
#line hidden
#nullable disable
            ));
            __builder.AddContent(86, "Remove");
            __builder.CloseElement();
            __builder.CloseElement();
#nullable restore
#line 48 "D:\Code\GakuGym\public\src\Client\UI\Pages\EditCategory.razor"
		}

#line default
#line hidden
#nullable disable
            __builder.OpenElement(87, "button");
            __builder.AddAttribute(88, "onclick", Microsoft.AspNetCore.Components.EventCallback.Factory.Create<Microsoft.AspNetCore.Components.Web.MouseEventArgs>(this, 
#nullable restore
#line 49 "D:\Code\GakuGym\public\src\Client\UI\Pages\EditCategory.razor"
                          OnSaveButtonClick

#line default
#line hidden
#nullable disable
            ));
            __builder.AddContent(89, "Save");
            __builder.CloseElement();
            __builder.CloseElement();
#nullable restore
#line 51 "D:\Code\GakuGym\public\src\Client\UI\Pages\EditCategory.razor"
}

#line default
#line hidden
#nullable disable
        }
        #pragma warning restore 1998
#nullable restore
#line 53 "D:\Code\GakuGym\public\src\Client\UI\Pages\EditCategory.razor"
 
	[Parameter]
	public Guid RouteCategoryId { get; set; }

	Category? category;

	string? categoryNameText;
	string? categoryDescriptionText;

	class CategoryField
	{
		public Guid guid;
		public string? name;
		public string? description;
		public string? interpretation;
	}

	List<CategoryField> fields = new();

	protected override async Task OnParametersSetAsync()
	{
		category = await API.GetCategory(RouteCategoryId);

		categoryNameText = category.name;
		categoryDescriptionText = category.description;

		fields = category.fields.Select(x => new CategoryField
		{
			guid           = x.guid,
			name           = x.name,
			description    = x.description,
			interpretation = x.type.ToString(),
		}).ToList();
	}

	void OnCloseClick()
	{
		NavigationManager.NavigateTo($"/fact-database/category/{RouteCategoryId}");		
	}

	void OnAddFieldClick()
	{
		fields.Add(new());
	}

	void OnRemoveFieldClick(CategoryField categoryField)
	{
		fields.Remove(categoryField);
	}

	async Task OnSaveButtonClick()
	{
		await API.UpdateCategory(new Category
		{
			guid        = category.guid,
			name        = categoryNameText,
			description = categoryDescriptionText,
			fields      = fields.Select(x => new Field
			              {
				               guid        = x.guid,
				               description = x.description,
				               name        = x.name,
				               type        = Enum.Parse<FieldType>(x.interpretation)
			              }).ToList()
		});

		NavigationManager.NavigateTo($"/fact-database/category/{RouteCategoryId}");
	}

#line default
#line hidden
#nullable disable
    }
}
#pragma warning restore 1591
