#pragma checksum "D:\Code\GakuGym\public\src\Client\UI\Pages\FactDatbase.razor" "{8829d00f-11b8-4213-878b-770e8597ac16}" "2572dcebbb48e4ef8941981875ecbe041544b470b2786fa58790634400c9fd9f"
// <auto-generated/>
#pragma warning disable 1591
namespace GakuGym.Client.UI.Pages
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Components;
#nullable restore
#line 1 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using System.Net.Http;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using System.Net.Http.Json;

#line default
#line hidden
#nullable disable
#nullable restore
#line 3 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using Microsoft.AspNetCore.Components.Forms;

#line default
#line hidden
#nullable disable
#nullable restore
#line 4 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using Microsoft.AspNetCore.Components.Routing;

#line default
#line hidden
#nullable disable
#nullable restore
#line 5 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using Microsoft.AspNetCore.Components.Web;

#line default
#line hidden
#nullable disable
#nullable restore
#line 6 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using Microsoft.AspNetCore.Components.WebAssembly.Http;

#line default
#line hidden
#nullable disable
#nullable restore
#line 7 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using Microsoft.JSInterop;

#line default
#line hidden
#nullable disable
#nullable restore
#line 8 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using GakuGym.Client;

#line default
#line hidden
#nullable disable
#nullable restore
#line 9 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using GakuGym.Common;

#line default
#line hidden
#nullable disable
    [Microsoft.AspNetCore.Components.RouteAttribute("/fact-database")]
    public partial class FactDatbase : BaseComponent
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.OpenElement(0, "div");
            __builder.AddAttribute(1, "id", "pageHeader");
            __builder.AddMarkupContent(2, "<span id=\"pageHeaderLeft\">Fact Database</span>\n    ");
            __builder.OpenElement(3, "span");
            __builder.AddAttribute(4, "id", "pageHeaderRight");
            __builder.OpenElement(5, "button");
            __builder.AddAttribute(6, "class", "SecondaryButton");
            __builder.AddAttribute(7, "onclick", Microsoft.AspNetCore.Components.EventCallback.Factory.Create<Microsoft.AspNetCore.Components.Web.MouseEventArgs>(this, 
#nullable restore
#line 5 "D:\Code\GakuGym\public\src\Client\UI\Pages\FactDatbase.razor"
                                                                         OnBackClick

#line default
#line hidden
#nullable disable
            ));
            __builder.AddMarkupContent(8, "<svg class=\"icon\"><use xlink:href=\"#back\"></use></svg>");
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.AddMarkupContent(9, "\n");
            __builder.OpenElement(10, "div");
            __builder.AddAttribute(11, "id", "pageBody");
            __builder.OpenElement(12, "div");
            __builder.AddAttribute(13, "class", "searchWrapper");
            __builder.AddMarkupContent(14, "<input type=\"text\" placeholder=\"Enter a search query\">\n        ");
            __builder.OpenElement(15, "button");
            __builder.AddAttribute(16, "onclick", Microsoft.AspNetCore.Components.EventCallback.Factory.Create<Microsoft.AspNetCore.Components.Web.MouseEventArgs>(this, 
#nullable restore
#line 10 "D:\Code\GakuGym\public\src\Client\UI\Pages\FactDatbase.razor"
                          OnSearchClick

#line default
#line hidden
#nullable disable
            ));
            __builder.AddMarkupContent(17, "<svg class=\"icon\"><use xlink:href=\"#search\"></use></svg>");
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.AddMarkupContent(18, "\n    ");
            __builder.OpenElement(19, "div");
            __builder.OpenElement(20, "div");
            __builder.AddAttribute(21, "class", "listHeader");
            __builder.AddMarkupContent(22, "<span>Domains</span>\n            ");
            __builder.OpenElement(23, "button");
            __builder.AddAttribute(24, "class", "SecondaryButton");
            __builder.AddAttribute(25, "onclick", Microsoft.AspNetCore.Components.EventCallback.Factory.Create<Microsoft.AspNetCore.Components.Web.MouseEventArgs>(this, 
#nullable restore
#line 15 "D:\Code\GakuGym\public\src\Client\UI\Pages\FactDatbase.razor"
                                                      OnDomainAddClick

#line default
#line hidden
#nullable disable
            ));
            __builder.AddMarkupContent(26, "<svg class=\"icon\"><use xlink:href=\"#add\"></use></svg>");
            __builder.CloseElement();
            __builder.CloseElement();
#nullable restore
#line 17 "D:\Code\GakuGym\public\src\Client\UI\Pages\FactDatbase.razor"
         if(domains != null)
        {
            

#line default
#line hidden
#nullable disable
#nullable restore
#line 19 "D:\Code\GakuGym\public\src\Client\UI\Pages\FactDatbase.razor"
             foreach(var domain in domains)
            {

#line default
#line hidden
#nullable disable
            __builder.OpenElement(27, "div");
            __builder.AddAttribute(28, "class", "card domainCard");
            __builder.AddAttribute(29, "onclick", Microsoft.AspNetCore.Components.EventCallback.Factory.Create<Microsoft.AspNetCore.Components.Web.MouseEventArgs>(this, 
#nullable restore
#line 21 "D:\Code\GakuGym\public\src\Client\UI\Pages\FactDatbase.razor"
                                                       () => OnDomainClick(domain)

#line default
#line hidden
#nullable disable
            ));
            __builder.OpenElement(30, "div");
            __builder.AddAttribute(31, "class", "DomainHeader");
            __builder.OpenElement(32, "span");
            __builder.AddAttribute(33, "class", "DomainName");
#nullable restore
#line (23,51)-(23,62) 25 "D:\Code\GakuGym\public\src\Client\UI\Pages\FactDatbase.razor"
__builder.AddContent(34, domain.name);

#line default
#line hidden
#nullable disable
            __builder.CloseElement();
            __builder.AddMarkupContent(35, "\n                        ");
            __builder.AddMarkupContent(36, "<svg class=\"icon\"><use xlink:href=\"#moreHorizontal\"></use></svg>");
            __builder.CloseElement();
            __builder.AddMarkupContent(37, "\n                    ");
            __builder.OpenElement(38, "span");
            __builder.AddAttribute(39, "class", "DomainDescription");
#nullable restore
#line (26,54)-(26,72) 25 "D:\Code\GakuGym\public\src\Client\UI\Pages\FactDatbase.razor"
__builder.AddContent(40, domain.description);

#line default
#line hidden
#nullable disable
            __builder.CloseElement();
            __builder.CloseElement();
#nullable restore
#line 28 "D:\Code\GakuGym\public\src\Client\UI\Pages\FactDatbase.razor"
            }

#line default
#line hidden
#nullable disable
#nullable restore
#line 28 "D:\Code\GakuGym\public\src\Client\UI\Pages\FactDatbase.razor"
             
        }

#line default
#line hidden
#nullable disable
            __builder.CloseElement();
            __builder.CloseElement();
        }
        #pragma warning restore 1998
#nullable restore
#line 34 "D:\Code\GakuGym\public\src\Client\UI\Pages\FactDatbase.razor"
 
    List<Domain>? domains;

    protected override async Task OnParametersSetAsync()
    {
        domains = await API.GetDomains();

        await base.OnParametersSetAsync();
    }

    void OnBackClick()
    {
        NavigationManager.NavigateTo($"/");
    }

    void OnSearchClick()
    {
        
    }

    void OnDomainClick(Domain domain)
    {
        NavigationManager.NavigateTo($"/fact-database/domain/{domain.guid}");    
    }

    void OnDomainAddClick()
    {
        NavigationManager.NavigateTo("/fact-database/new-domain");
    }

#line default
#line hidden
#nullable disable
    }
}
#pragma warning restore 1591
