#pragma checksum "D:\Code\GakuGym\public\src\Client\UI\Pages\DomainPage.razor" "{8829d00f-11b8-4213-878b-770e8597ac16}" "e811e7e4bcc5bfca3bc7966f8bd87e11281ebc1a45d869f3fb5af6938c29389a"
// <auto-generated/>
#pragma warning disable 1591
namespace GakuGym.Client.UI.Pages
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Components;
#nullable restore
#line 1 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using System.Net.Http;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using System.Net.Http.Json;

#line default
#line hidden
#nullable disable
#nullable restore
#line 3 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using Microsoft.AspNetCore.Components.Forms;

#line default
#line hidden
#nullable disable
#nullable restore
#line 4 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using Microsoft.AspNetCore.Components.Routing;

#line default
#line hidden
#nullable disable
#nullable restore
#line 5 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using Microsoft.AspNetCore.Components.Web;

#line default
#line hidden
#nullable disable
#nullable restore
#line 6 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using Microsoft.AspNetCore.Components.WebAssembly.Http;

#line default
#line hidden
#nullable disable
#nullable restore
#line 7 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using Microsoft.JSInterop;

#line default
#line hidden
#nullable disable
#nullable restore
#line 8 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using GakuGym.Client;

#line default
#line hidden
#nullable disable
#nullable restore
#line 9 "D:\Code\GakuGym\public\src\Client\_Imports.razor"
using GakuGym.Common;

#line default
#line hidden
#nullable disable
    [Microsoft.AspNetCore.Components.RouteAttribute("/fact-database/domain/{RouteParamDomainId:guid}")]
    public partial class DomainPage : BaseComponent
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
#nullable restore
#line 4 "D:\Code\GakuGym\public\src\Client\UI\Pages\DomainPage.razor"
 if (domain != null)
{

#line default
#line hidden
#nullable disable
            __builder.OpenElement(0, "div");
            __builder.AddAttribute(1, "id", "pageHeader");
            __builder.OpenElement(2, "span");
            __builder.AddAttribute(3, "id", "pageHeaderLeft");
            __builder.AddContent(4, "Domain - ");
#nullable restore
#line (7,42)-(7,53) 24 "D:\Code\GakuGym\public\src\Client\UI\Pages\DomainPage.razor"
__builder.AddContent(5, domain.name);

#line default
#line hidden
#nullable disable
            __builder.CloseElement();
            __builder.AddMarkupContent(6, "\n\t\t");
            __builder.OpenElement(7, "span");
            __builder.AddAttribute(8, "id", "pageHeaderRight");
            __builder.OpenElement(9, "button");
            __builder.AddAttribute(10, "class", "SecondaryButton");
            __builder.AddAttribute(11, "onclick", Microsoft.AspNetCore.Components.EventCallback.Factory.Create<Microsoft.AspNetCore.Components.Web.MouseEventArgs>(this, 
#nullable restore
#line 9 "D:\Code\GakuGym\public\src\Client\UI\Pages\DomainPage.razor"
                                                      OnEditClick

#line default
#line hidden
#nullable disable
            ));
            __builder.AddMarkupContent(12, "<svg class=\"icon\"><use xlink:href=\"#edit\"></use></svg>");
            __builder.CloseElement();
            __builder.OpenElement(13, "button");
            __builder.AddAttribute(14, "class", "SecondaryButton");
            __builder.AddAttribute(15, "onclick", Microsoft.AspNetCore.Components.EventCallback.Factory.Create<Microsoft.AspNetCore.Components.Web.MouseEventArgs>(this, 
#nullable restore
#line 10 "D:\Code\GakuGym\public\src\Client\UI\Pages\DomainPage.razor"
                                                      OnBackClick

#line default
#line hidden
#nullable disable
            ));
            __builder.AddMarkupContent(16, "<svg class=\"icon\"><use xlink:href=\"#back\"></use></svg>");
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.AddMarkupContent(17, "\n\t");
            __builder.OpenElement(18, "div");
            __builder.AddAttribute(19, "id", "pageBody");
            __builder.OpenElement(20, "div");
            __builder.AddAttribute(21, "id", "domainDescription");
#nullable restore
#line (15,5)-(15,23) 25 "D:\Code\GakuGym\public\src\Client\UI\Pages\DomainPage.razor"
__builder.AddContent(22, domain.description);

#line default
#line hidden
#nullable disable
            __builder.CloseElement();
            __builder.AddMarkupContent(23, "\n\t\t");
            __builder.OpenElement(24, "div");
            __builder.AddAttribute(25, "class", "listHeader");
            __builder.AddMarkupContent(26, "<span>Categories</span>\n\t\t\t");
            __builder.OpenElement(27, "button");
            __builder.AddAttribute(28, "class", "SecondaryButton");
            __builder.AddAttribute(29, "onclick", Microsoft.AspNetCore.Components.EventCallback.Factory.Create<Microsoft.AspNetCore.Components.Web.MouseEventArgs>(this, 
#nullable restore
#line 19 "D:\Code\GakuGym\public\src\Client\UI\Pages\DomainPage.razor"
                                                      AddCategoryClick

#line default
#line hidden
#nullable disable
            ));
            __builder.AddMarkupContent(30, "<svg class=\"icon\"><use xlink:href=\"#add\"></use></svg>");
            __builder.CloseElement();
            __builder.CloseElement();
#nullable restore
#line 21 "D:\Code\GakuGym\public\src\Client\UI\Pages\DomainPage.razor"
         foreach (var category in domain.categories)
		{

#line default
#line hidden
#nullable disable
            __builder.OpenElement(31, "div");
            __builder.AddAttribute(32, "class", "card categoryCard");
            __builder.AddAttribute(33, "onclick", Microsoft.AspNetCore.Components.EventCallback.Factory.Create<Microsoft.AspNetCore.Components.Web.MouseEventArgs>(this, 
#nullable restore
#line 23 "D:\Code\GakuGym\public\src\Client\UI\Pages\DomainPage.razor"
                                                     () => OnCategoryClick(category)

#line default
#line hidden
#nullable disable
            ));
            __builder.OpenElement(34, "div");
#nullable restore
#line (24,11)-(24,24) 25 "D:\Code\GakuGym\public\src\Client\UI\Pages\DomainPage.razor"
__builder.AddContent(35, category.name);

#line default
#line hidden
#nullable disable
            __builder.CloseElement();
            __builder.AddMarkupContent(36, "\n\t\t\t\t");
            __builder.OpenElement(37, "div");
#nullable restore
#line (25,11)-(25,31) 25 "D:\Code\GakuGym\public\src\Client\UI\Pages\DomainPage.razor"
__builder.AddContent(38, category.description);

#line default
#line hidden
#nullable disable
            __builder.CloseElement();
            __builder.CloseElement();
#nullable restore
#line 27 "D:\Code\GakuGym\public\src\Client\UI\Pages\DomainPage.razor"
		}

#line default
#line hidden
#nullable disable
            __builder.CloseElement();
#nullable restore
#line 29 "D:\Code\GakuGym\public\src\Client\UI\Pages\DomainPage.razor"
}

#line default
#line hidden
#nullable disable
        }
        #pragma warning restore 1998
#nullable restore
#line 32 "D:\Code\GakuGym\public\src\Client\UI\Pages\DomainPage.razor"
 
	[Parameter]
	public Guid RouteParamDomainId { get; set; }

	Domain? domain;

	protected override async Task OnParametersSetAsync()
	{
		domain = await API.GetDomain(RouteParamDomainId);		
	}

	void OnEditClick()
	{
		NavigationManager.NavigateTo($"/fact-database/domain/{domain.guid}/edit");
	}

	void OnBackClick()
	{
		NavigationManager.NavigateTo("/fact-database");
	}

	void AddCategoryClick()
	{
		NavigationManager.NavigateTo($"/fact-database/domain/{domain.guid}/add-category");
	}

	void OnCategoryClick(Category category)
	{
		NavigationManager.NavigateTo($"/fact-database/category/{category.guid}");
	}

#line default
#line hidden
#nullable disable
    }
}
#pragma warning restore 1591
